- Cargo.lock
- Cargo.toml
- crates/pixi-build/Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/cli.rs
In conjunction with https://github.com/prefix-dev/pixi/pull/2251
> fix: use cache and virtual packages

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/build_script.j2
- crates/pixi-build/src/bin/pixi-build-cmake/build_script.rs
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/cli.rs
Implements incremental compilation for cmake
Requires https://github.com/prefix-dev/pixi/pull/2268
> feat: incremental cmake compilation

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/manifest_ext.rs
* add support for channels in manifest
* add a small test to validate what we expect from manifest
> feat: add support for newer manifest

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/manifest_ext.rs
- crates/pixi-build/src/tools.rs
Upgrade the build types.
Still depends on some git sources, but should be fine 😎
> feat: pixi-build backend upgrade

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/dependencies.rs
- crates/pixi-build/src/manifest_ext.rs
Bumps pixi and incorporates the changes from https://github.com/prefix-dev/pixi/pull/2601
> chore: update build system changes

- .github/workflows/pre-commit.yml
- .github/workflows/rattler-build.yml
- .github/workflows/rust-compile.yml
- .pre-commit-config.yaml
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
- pixi.lock
- pixi.toml
- tests/recipe/boltons/recipe.yaml
Let's enforce reasonable standards early on :)
> feat: pre-commit and more extensive rust linting

- README.md
Add simple README describing the project somewhat.
> doc: add simple readme

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
- crates/pixi-build/src/cli.rs
- crates/pixi-build/src/protocol.rs
- crates/pixi-build/src/server.rs
- crates/pixi-build/src/tools.rs
This is the companion PR for: https://github.com/prefix-dev/pixi/pull/2831
> feat: split intialize and capabilities

- .gitignore
- Cargo.lock
- Cargo.toml
- crates/pixi-build/Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-cmake/config.rs
- crates/pixi-build/src/bin/pixi-build-python/config.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
- crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
- crates/pixi-build/src/cli.rs
- crates/pixi-build/src/manifest_ext.rs
This PR updates the backends to support https://github.com/prefix-dev/pixi/pull/2731
> chore: update package keys

- .github/workflows/rust-compile.yml
I know it's kind of heresy, but let's try this until we use pixi in CI: https://github.com/prefix-dev/pixi-build-backends/issues/53
> feat: install lzma for now until we convert to pixi

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-python/python.rs
Updates the protocol to talk like https://github.com/prefix-dev/pixi/pull/2939
> fix: protocol update

- .github/workflows/rattler-build.yml
Disable actual rattler-build upload on a forked PR, otherwise this always fails.
> fix: dont run rattler-build upload on fork

- crates/pixi-build/src/bin/pixi-build-cmake/build_script.j2
- crates/pixi-build/src/bin/pixi-build-cmake/build_script.rs
- crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
- crates/pixi-build/src/bin/pixi-build-cmake/config.rs
Some experimental work to build more complicated CMake examples.
> feat: use extra args from cmake configuration when building

- Cargo.lock
- Cargo.toml
- crates/pixi-build/src/bin/pixi-build-rattler-build/config.rs
- crates/pixi-build/src/bin/pixi-build-rattler-build/main.rs
- crates/pixi-build/src/bin/pixi-build-rattler-build/protocol.rs
- crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
- crates/pixi-build/src/manifest_ext.rs
See https://github.com/prefix-dev/pixi/pull/3141 for an example of how this is used
> feat: adapt rattler-build-backend to allow debug logging

- crates/pixi-build-rust/pixi.toml
> release: pixi-build-rust-0.1.4

- Cargo.lock
- crates/pixi-build-rust/Cargo.toml
> fix: bump Cargo.toml pixi-build-rust-0.1.4

- .github/workflows/rattler-build.yml
- scripts/generate_version_matrix.py
On windows it didn't set the env variable, because we didn't use bash terminal
> fix: set correct env variable

- Cargo.toml
This should fix https://github.com/prefix-dev/pixi/issues/3505
> fix: enable `rustls-tls` on `rattler-build`

- Cargo.lock
- RELEASE.md
- crates/pixi-build-cmake/Cargo.toml
- crates/pixi-build-cmake/pixi.toml
- crates/pixi-build-python/Cargo.toml
- crates/pixi-build-python/pixi.toml
- crates/pixi-build-rattler-build/Cargo.toml
- crates/pixi-build-rattler-build/pixi.toml
- crates/pixi-build-rust/Cargo.toml
- crates/pixi-build-rust/pixi.toml
- cmake: 0.1.5
- python: 0.1.5
- rattler-build: 0.1.4
- rust: 0.1.6
> release: update all backends

- Cargo.lock
- crates/pixi-build-cmake/src/cmake.rs
- crates/pixi-build-cmake/src/config.rs
- crates/pixi-build-python/src/config.rs
- crates/pixi-build-python/src/python.rs
- crates/pixi-build-rust/Cargo.toml
- crates/pixi-build-rust/src/config.rs
- crates/pixi-build-rust/src/rust.rs
> feat: allow to set environment variables from configuration

- crates/pixi-build-cmake/src/config.rs
- crates/pixi-build-python/src/config.rs
- crates/pixi-build-python/src/python.rs
- crates/pixi-build-rattler-build/src/config.rs
- crates/pixi-build-rust/src/config.rs
> fix: optional env

- scripts/generate_version_matrix.py
Unfortunately, this also got formatted quite heavily by ruff
> ci: use ubuntu latest

- Cargo.lock
- crates/pixi-build-rust/Cargo.toml
- crates/pixi-build-rust/pixi.toml
That should unblock our release process
> chore: bump pixi-build-rust

- Cargo.lock
- crates/pixi-build-rattler-build/Cargo.toml
- crates/pixi-build-rattler-build/pixi.toml
That should make Pixi CI green again
> bump: pixi build rattler build

- crates/pixi-build-rattler-build/src/protocol.rs
I misread the code and thought that we pass the recipe dir as relative path. Instead it's the source that can be relative and needs to be turned into an absolute path.
> fix: compute relative path for source dirs

- Cargo.lock
- crates/pixi-build-cmake/Cargo.toml
- crates/pixi-build-cmake/pixi.toml
- crates/pixi-build-python/Cargo.toml
- crates/pixi-build-python/pixi.toml
- crates/pixi-build-rattler-build/Cargo.toml
- crates/pixi-build-rattler-build/pixi.toml
- crates/pixi-build-rust/Cargo.toml
- crates/pixi-build-rust/pixi.toml
In order to prepare for release
> bump: version numbers

- Cargo.lock
- crates/pixi-build-cmake/Cargo.toml
- crates/pixi-build-python/Cargo.toml
- crates/pixi-build-rattler-build/Cargo.toml
- crates/pixi-build-rust/Cargo.toml
Let's prepare for another release
> bump version numbers

- pixi.lock
- pixi.toml
See also https://github.com/prefix-dev/pixi-build-backends/pull/179#issuecomment-2912442136
> chore: pin patchelf

- recipe/pixi-build-cmake.yaml
- recipe/pixi-build-python.yaml
- recipe/pixi-build-rattler-build.yaml
- recipe/pixi-build-rust.yaml
I forgot to update the run depencies in our rename tango
> fix: API package name

- Cargo.lock
- crates/pixi-build-rattler-build/Cargo.toml
Bump pixi-build-rattler-build backend
> bump: pixi-build-rattler-build 0.15.0

- Cargo.lock
- crates/pixi-build-cmake/Cargo.toml
- crates/pixi-build-mojo/Cargo.toml
- crates/pixi-build-python/Cargo.toml
- crates/pixi-build-rattler-build/Cargo.toml
- crates/pixi-build-rust/Cargo.toml
Preparing a release to get the fix from #271 in.
> chore: update backend crates versions

- .github/workflows/build-upload.yml
- scripts/generate-matrix.py
This allows us to release single packages
> feat(ci): add single package building the the build ci

- .github/workflows/python-bindings.yml
- backends/pixi-build-ros/pixi.lock
- backends/pixi-build-ros/pixi.toml
- backends/pixi-build-ros/src/pixi_build_ros/config.py
- backends/pixi-build-ros/src/pixi_build_ros/ros_generator.py
- backends/pixi-build-ros/src/pixi_build_ros/utils.py
- backends/pixi-build-ros/tests/data/other_package_map.yaml
- backends/pixi-build-ros/tests/test_package_map.py
- docs/backends/pixi-build-ros.md
- py-pixi-build-backend/pixi.toml
- Adding documentation about the custom dependency mapping
- Change the tests a little bit
- Fix an issue with the map being searched relative to the CWD.
> chore: improve pixi config ros
