prefix-dev/pixi-build-backends

crates/pixi-build/src/bin/pixi-build-cmake/build_script.j2

Speeds up incremental cmake builds drastically when the changes are minimal

perf: add CMakeCache.txt check to avoid reconfiguring

---

pixi.toml

these tasks should automate a little the process of installing pixi-build-backends during the development

feat: add pixi task for installing backends

---

.github/workflows/rattler-build.yml

Adds osx64, so that a conda package would be built for this. We need this for testing in pixi ci.

feat: add osx64 as a build platform

---

Cargo.lock
Cargo.toml
crates/pixi-build/Cargo.toml
crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
crates/pixi-build/src/bin/pixi-build-python/python.rs
crates/pixi-build/src/bin/pixi-build-rattler-build/main.rs
crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
crates/pixi-build/src/lib.rs
crates/pixi-build/src/manifest_ext.rs
crates/pixi-build/src/tools.rs
crates/pixi-build/src/utils/temporary_recipe.rs
recipe/recipe.yaml
tests/recipe/boltons_recipe.yaml

This PR aims to add a new backend - `pixi-build-rattler-build`. It should be responsible for building a `recipe.yaml` that is located nearby pixi.toml, so user can just run pixi build.
Right now we have already using `rattler-build` in our other backends , pixi-cmake and pixi-python, where we create artifically a recipe from manifest but we are using `rattler-build` API directly there.
In this implementation, I'm using `rattler-build` API through `tools::RatterlBuild` to build a `real` recipe. 
My vision is that every backend that it is using  so we can hide rattler-build implementation behind that struct, and only that struct is responsible to interact with rattler-build. In this way, we don't need to leak all rattler-build types in pixi-backends and we could stick to the same workflow. …

feat: add new pixi-build-backend

---

crates/pixi-build/src/bin/pixi-build-cmake/snapshots/pixi_build_cmake__cmake__tests__setting_host_and_build_requirements-2.snap
crates/pixi-build/src/bin/pixi-build-cmake/snapshots/pixi_build_cmake__cmake__tests__setting_host_and_build_requirements.snap
crates/pixi-build/src/bin/pixi-build-python/snapshots/pixi_build_python__python__tests__noarch_none.snap
crates/pixi-build/src/bin/pixi-build-python/snapshots/pixi_build_python__python__tests__noarch_python.snap
crates/pixi-build/src/bin/pixi-build-python/snapshots/pixi_build_python__python__tests__setting_host_and_build_requirements-2.snap
crates/pixi-build/src/bin/pixi-build-python/snapshots/pixi_build_python__python__tests__setting_host_and_build_requirements.snap
crates/pixi-build/src/dependencies.rs

So that `variants` work the rattler-build way.

feat: turn wildcards into name-only specs

---

Cargo.lock
Cargo.toml
crates/pixi-build/src/bin/pixi-build-python/build_script.j2
crates/pixi-build/src/bin/pixi-build-python/build_script.rs
crates/pixi-build/src/bin/pixi-build-python/python.rs
crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
crates/pixi-build/src/cli.rs

Only `pixi-build-python` handles the `editable` parameter

feat: support editable installs for `pixi build`

---

Cargo.lock
Cargo.toml
crates/pixi-build/src/bin/pixi-build-python/python.rs
crates/pixi-build/src/tools.rs

Switching to my repo was necessary to have green CI. Now that everything is merged, we can go back.

fix: switch `pixi` dependency back to prefix-dev

---

crates/pixi-build/src/bin/pixi-build-cmake/build_script.j2

As discussed in #39 this PR adds `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to the default cmake invocation. This will [make cmake generate the `compile_commands.json` file in the build directory.](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) 
In the future it would probably be good to couple this to the "profiles" feature.

feat: add `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

---

crates/pixi-build/src/tools.rs

I am not sure if this helps but this is what the source of `ParseErrors` looks like ... 
```rust
/// Collection of parse errors to build related diagnostics
#[derive(Error, Debug, Diagnostic)]
#[error("Failed to parse recipe")]
pub struct ParseErrors {
#[related]
errs: Vec<ParsingError>,
}
```

add into_diagnostic

---

crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
crates/pixi-build/src/bin/pixi-build-python/python.rs

Refactors the code to use passed in variants for both build and metadata.

feat: variants in metadata

---

Cargo.lock
Cargo.toml
crates/pixi-build/Cargo.toml
crates/pixi-build/src/bin/pixi-build-cmake/cmake.rs
crates/pixi-build/src/bin/pixi-build-cmake/config.rs
crates/pixi-build/src/bin/pixi-build-python/config.rs
crates/pixi-build/src/bin/pixi-build-python/python.rs
crates/pixi-build/src/bin/pixi-build-rattler-build/rattler_build.rs
crates/pixi-build/src/build_types_ext.rs
crates/pixi-build/src/cli.rs
crates/pixi-build/src/dependencies.rs
crates/pixi-build/src/lib.rs
crates/pixi-build/src/variants.rs
pixi.lock
pixi.toml

Remove reading the manifests from the backends and depends on the new project_model in pixi. Companion PR in pixi: https://github.com/prefix-dev/pixi/pull/2903
Some explanation why I've designed it in this way. I figured we could create a common type of functionality through traits and once these are defined, when there is a protocol update you only need to implement the traits for the updated protocol. Next, we can type the backends on these traits and select on basis of the project model version.
I'll add this functionality in a follow-up PR or when we actually require the change :)

feat: remove reading from the manifest 

---

.github/workflows/rattler-build.yml

Attempts to fix uploading again.

feat: fix  uploading

---

.github/workflows/rattler-build.yml

Only release when a tag is pushed.
The build should also run in a PR but the publish step will be skipped, because of the `event.push`.

feat: on release on tag

---

crates/pixi-build/src/bin/pixi-build-cmake/protocol.rs
crates/pixi-build/src/bin/pixi-build-python/protocol.rs
crates/pixi-build/src/bin/pixi-build-rattler-build/protocol.rs
crates/pixi-build/src/cli.rs
crates/pixi-build/src/protocol.rs
crates/pixi-build/src/server.rs

That way they fit with the RPC method names `conda/getMetadata` and `conda/build`

fix: protocol method names

---

scripts/generate_version_matrix.py

``` git describe --tags --exact-match``` doesn't work when you have multiple tags on the same commit ( which we plan to have)
this approach will use git tag --points-at HEAD to ask for the entire list of the tags for the release commit.

feat: support multiple tags

---

.github/workflows/enforce-sha.yaml
.github/workflows/pre-commit.yml
.github/workflows/rattler-build.yml
.github/workflows/rust-compile.yml

- pin external actions
- enforce sha also in the future
For motivation see https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://michaelheap.com/pin-your-github-actions/

ci: pin github actions

---

crates/pixi-build-backend/src/traits/targets.rs
crates/pixi-build-rust/src/build_script.j2
crates/pixi-build-rust/src/build_script.rs
crates/pixi-build-rust/src/rust.rs

unblock: https://github.com/prefix-dev/pixi-build-backends/pull/98
Sometimes when building a rust-based conda package, you may need or not openssl in host dependencies in order to build it.
This PR only `optionally` export `OPENSSL_DIR` if OpenSSL is present in any dependencies

fix: export openssl

---

crates/pixi-build-cmake/src/protocol.rs
crates/pixi-build-python/src/protocol.rs
crates/pixi-build-rust/src/protocol.rs

Preparation for https://github.com/prefix-dev/pixi-build-backends/pull/98
The reason to split up these changes - I want to make a proper release of backends.

fix: use correct build and host platform

---

Cargo.lock
crates/pixi-build-cmake/Cargo.toml
crates/pixi-build-rust/Cargo.toml

release: bump pixi-build-rust 0.1.5 and pixi-build-cmake 0.1.4

---

crates/pixi-build-cmake/src/build_script.j2

Fixes https://github.com/prefix-dev/pixi/issues/3436
The cmake build backend checked if a `CMakeCache.txt` file exists to determine if CMake needed to be rerun to reconfigure the project. However, if the first configure step failed  the `CMakeCache.txt` was still created even though on a subsequent run `cmake` should be rerun. 
We could just not have the check and run `cmake` on every invocation, but that adds significant overhead. Instead, we can check if the `build.ninja` file exists. After that, we can always invoke `cmake --build` because if any cmake file changed ninja itself will reconfigure the project.

fix: check if `build.ninja` exists to reconfigure cmake

---

crates/pixi-build-python/src/protocol.rs
crates/pixi-build-rattler-build/src/protocol.rs

Also adds input globs for metadata which I think should help with caching? 
We glob the whole folder because it is possible that e.g. `build.sh` or a patch changes. 
Ideally we would probably also glob the `source` folder ... 
Or even more ideally we would have methods to find _all_ referenced (local) files from a `recipe.yaml` and add them all to the input hash.

feat: glob recipe.yaml parent directory more properly

---

RELEASE.md
crates/pixi-build-cmake/pixi.toml
crates/pixi-build-python/pixi.toml
crates/pixi-build-rattler-build/pixi.toml
crates/pixi-build-rust/pixi.toml

Our release docs wasn't up-to-date unfortunately.
We should automate this more in general.
At the moment, releasing all crates takes effort and is error prone

chore: update pixi.toml

---

Cargo.lock
crates/pixi-build-rattler-build/Cargo.toml
crates/pixi-build-rattler-build/src/protocol.rs

The current system has two problems:
- they contain absolute paths which will not error on unix, but also not do what we want
- they contain `\` on Windows, which wax will not accept at all
The correct behavior should be to get the relative path to the source directory and then join the components with "/"

fix: rattler-build backend globs

---

crates/pixi-build-rattler-build/src/protocol.rs

Let's remove this code path for now until we need it for https://github.com/prefix-dev/pixi/issues/3778.
Then we should make sure to pass absolute paths, since `pathdiff` cannot compare absolute paths with relative ones.

fix: relative source paths `pixi-build-rattler-build`

---

crates/pixi-build-rattler-build/src/protocol.rs
crates/pixi-build-rattler-build/src/rattler_build.rs

recipe files are detected under different names and directories. This PR accounts for that.

fix: pixi-build-rattler-build globs

---

pixi.toml
scripts/default_linker_osx_64.sh

This should unblock osx-64 releases.
See also https://github.com/rust-lang/rust/issues/140686

fix: use default linker on osx-64

---

Cargo.lock
crates/pixi-build-rattler-build/Cargo.toml
crates/pixi-build-rattler-build/src/protocol.rs

Fix multi-output handling of `recipe.yaml`.
- `pixi-build-rattler-build` used to return an empty hashmap for `sources`
- However, a recipe output can depend on an output in the same recipe
- Since Pixi requires all source dependencies to either be directly requested or be transitively requested in the `sources` field, the missing `sources` entry lead to a permanently out-of-date lock file
We should merge in the following order:
- https://github.com/prefix-dev/pixi/pull/3961
- https://github.com/prefix-dev/pixi-build-backends/pull/203
- https://github.com/prefix-dev/pixi-build-testsuite/pull/5

Return source records with pixi-build-rattler-build

---

docs/backends/pixi-build-cmake.md
docs/backends/pixi-build-python.md
docs/backends/pixi-build-rattler-build.md
docs/backends/pixi-build-rust.md

That way it's a bit more readable

docs: change configuration to list

---

Cargo.lock
Cargo.toml
crates/pixi-build-cmake/Cargo.toml
crates/pixi-build-python/Cargo.toml
crates/pixi-build-rattler-build/Cargo.toml
crates/pixi-build-rust/Cargo.toml
recipe/pixi-build-cmake.yaml
recipe/pixi-build-python.yaml
recipe/pixi-build-rattler-build.yaml
recipe/pixi-build-rust.yaml

The `pixi-build-rattler-build` recipe had a wrong path. I also aligned more with the conda-forge recipes. Also bumps the versions to `0.3.0` now that we enabled build v1 api.

fix: recipes

---

.github/workflows/rust.yml
.github/workflows/testsuite.yml

We were not using the cache for Pixi envs in PRs which resulted in up to 5 minute installations before running the tests. 
This replaces:
```
cache: ${{ github.ref == 'refs/heads/main' }}
```
with
```
cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
```
Meaning we decide if we cache based on the name but using the cache is always turned on.

ci: replace using of the cache logic with writing it

---

crates/pixi-build-backend/src/specs_conversion.rs
crates/pixi-build-cmake/src/snapshots/pixi_build_cmake__tests__cxx_is_in_build_requirements.snap
crates/pixi-build-cmake/src/snapshots/pixi_build_cmake__tests__cxx_is_not_added_if_gcc_is_already_present.snap
crates/pixi-build-mojo/src/snapshots/pixi_build_mojo__tests__max_is_in_build_requirements.snap
crates/pixi-build-mojo/src/snapshots/pixi_build_mojo__tests__max_is_not_added_if_max_is_already_present.snap
crates/pixi-build-mojo/src/snapshots/pixi_build_mojo__tests__mojo_bin_is_set.snap
crates/pixi-build-mojo/src/snapshots/pixi_build_mojo__tests__mojo_pkg_is_set.snap
crates/pixi-build-python/src/snapshots/pixi_build_python__tests__pip_is_in_host_requirements.snap
crates/pixi-build-python/src/snapshots/pixi_build_python__tests__python_is_not_added_if_already_present.snap
crates/pixi-build-rust/src/snapshots/pixi_build_rust__tests__rust_is_in_build_requirements.snap
crates/pixi-build-rust/src/snapshots/pixi_build_rust__tests__rust_is_not_added_if_already_present.snap

Previously, rattler-build treated `- python *` as `not` a variant, so we missed it.
This fix will convert from Binary matchspec `python * ` to just `python`, so rattler-build could discover it

fix: variant discovery from recipe

---

README.md
docs/backends/pixi-build-cmake.md
docs/backends/pixi-build-mojo.md
docs/backends/pixi-build-python.md
docs/backends/pixi-build-rattler-build.md
docs/backends/pixi-build-rust.md
docs/index.md

Pointing users to use `conda-forge` first.

docs: direct to conda-forge instead of `pixi-build-backends`

---

Cargo.lock
crates/pixi-build-backend/src/intermediate_backend.rs
crates/pixi-build-rattler-build/src/protocol.rs
py-pixi-build-backend/Cargo.lock

Bumps rattler-build to get https://github.com/prefix-dev/rattler-build/pull/1813 in. This will ensure that incremental compilation works!

fix: preserve working directory for incremental compilation

---

.github/workflows/setup-dev-drive.ps1

rattler-build isn't happy with mixed path separators

fix: dev drive script

---

.github/workflows/python-bindings.yml
py-pixi-build-backend/pixi.lock
py-pixi-build-backend/pixi.toml
py-pixi-build-backend/pyproject.toml
recipe/pixi-build-py-pixi-build-backend/recipe.yaml
scripts/generate-matrix.py

This will make developing the py bindings slightly easier, and will add a release workflow to the ci for it.

chore: improve py-pixi-build-backend workspace

---

scripts/generate-matrix.py

Should resolve this: https://github.com/prefix-dev/pixi-build-backends/actions/runs/16940331357/job/48007517668

fix: run osx-64 builds on osx-arm64

---

recipe/py-pixi-build-backend/recipe.yaml

The C compiler resulting in the wrong Rust compiler being used on Windows.
https://github.com/prefix-dev/pixi-build-backends/actions/runs/16940331357/job/48007517688

fix: remove c compiler from recipe

---

crates/pixi-build-python/src/build_script.j2
py-pixi-build-backend/examples/pixi-build-python/pixi_build_python/build_script.py

Hi,
When I try to build a pixi package with pixi-build-python, the build script fail because my project's path contains spaces. Currently the generated conda_build.sh script does not quote the the path when running installation with uv, as shown in this example:
```sh
#!/bin/bash
if [ -z ${CONDA_BUILD+x} ]; then
source "/Users/valfvo/Library/Mobile Documents/com~apple~CloudDocs/projects/<redacted>/.pixi/build/work/utils-9onpsMVFaTY/work/build_env.sh"
fi
uv pip install --python $PYTHON -vv --no-deps --no-build-isolation --editable /Users/valfvo/Library/Mobile Documents/com~apple~CloudDocs/projects/<redacted>
```
This results in uv not finding python:
```
| - Running build script
│ │ DEBUG uv 0.8.12
│ │ DEBUG Marking explicit source tree for reinstall: …
```

fix: allow spaces within paths in build script

---

crates/pixi-build-backend/src/intermediate_backend.rs
crates/pixi-build-rattler-build/src/protocol.rs

fix: `Cleanup` -> `Preserve` for non- rattler-build backends

---

py-pixi-build-backend/pixi.lock
py-pixi-build-backend/pixi.toml

Using the compiler setting for the `py-pixi-build-backend`:
```
[package.build.config]
compilers = ["rust"]
```

fix: use rust compiler for building bindings

---

backends/pixi-build-ros/templates/build_ament_cmake.sh

This fix is mostly focused for linux platform, as it can only happen under this condition in the build script.
```
f [[ $target_platform =~ linux.* ]]
```
Tested on Mac by adding this in the build script
```
touch jorik.txt
ln -sf jorik.txt ${BUILD_PREFIX}/jorik_link.txt
```

fix: add force option for symbolic linking

---

crates/pixi-build-rattler-build/src/protocol.rs
crates/pixi-build-rattler-build/src/snapshots/pixi_build_rattler_build__protocol__tests__conda_outputs@boltons__recipe.yaml.snap
crates/pixi-build-rattler-build/src/snapshots/pixi_build_rattler_build__protocol__tests__conda_outputs@pin-subpackage-variants__recipe.yaml.snap
crates/pixi-build-rattler-build/src/snapshots/pixi_build_rattler_build__protocol__tests__conda_outputs@pin-subpackage__recipe.yaml.snap
crates/pixi-build-rattler-build/src/snapshots/pixi_build_rattler_build__protocol__tests__conda_outputs@variants__recipe.yaml.snap

Should fix prefix-dev/pixi#4500.

fix(rattler-build): add recipe.yaml to input globs

---

crates/pixi-build-rattler-build/src/protocol.rs

Use the `**` globs instead of `*/**`. The latter does not match files in the current directory for ignore and other glob implementations, wax was incorrect in that regard. We need this when switching to: https://github.com/prefix-dev/pixi/pull/4578. (This PR is needed to fix build errors there).
In draft until I verify the behavior completely.

feat: change glob types

---

backends/pixi-build-ros/pixi.lock
backends/pixi-build-ros/pixi.toml
backends/pixi-build-ros/src/pixi_build_ros/ros_generator.py
backends/pixi-build-ros/src/pixi_build_ros/utils.py
backends/pixi-build-ros/tests/conftest.py
backends/pixi-build-ros/tests/test_package_map.py
pixi.toml

This allows for inline mappings such as:
```
extra-package-mappings = [
{ mapping = {"ros-custom" = {ros =  ["ros-custom", "ros-custom-msgs"] },
"conda-custom" = {conda = ["conda-pkg"]}},
{ file = "./corp-mappings/config.yaml" }
]
```
While keeping the default as just being a path/file. 
I also changed that the order is loaded in "reverse", such that the first entry has highest priority (as with the channels).

feat(ros): add inline package mappings

---

backends/pixi-build-ros/src/pixi_build_ros/config.py
backends/pixi-build-ros/src/pixi_build_ros/ros_generator.py
backends/pixi-build-ros/src/pixi_build_ros/utils.py

Previously we incorrectly assumed that input of `extract_input_globs_from_build` was `ROSBackendConfig`. In fact it was a dict, which we had to manually convert.
I also refactored code a little bit to use `ROSBackendConfig` in type annotation of `get_build_input_globs`.

fix(ros): pass extra-input-globs

---

backends/pixi-build-ros/pixi.lock
backends/pixi-build-ros/pixi.toml
backends/pixi-build-ros/src/pixi_build_ros/metadata_provider.py
backends/pixi-build-ros/tests/data/package_xmls/broken.xml
backends/pixi-build-ros/tests/test_meta_data_provider.py

Allows "TODO" to be in the license field of a `package.xml`
While I would like to change this in the future, there are to many places where this is still used, so it would be annoying if you would have to change other people's code to get pixi to work. 
Working on this, I also found out that the backend was ignoring broken package.xml's and that resulted in completely useless errors. This should now tell the user a package.xml is not in a readable state.

fix: Skip TODO license
